### ISSUE TITLE
alloc-test uses incorrect types

### ISSUE THREAD

**Issue by richfelker** [daanx/mimalloc-bench#10]
`alloc-test` uses `size_t` to store time intervals, and performs arithmetic with large multiplications on them without promoting to a larger type. This causes integer overflows and invalid results on 32-bit targets that aren't extremely fast.

Some other tests may have similar issues; I haven't checked yet.

**Comment by daanx** [comment]
Ah thanks! I will look into this. Apologies for the late reply, it seems I wasn't getting notifications :-(
