### ISSUE TITLE
Add rocksdb to the benchmarks

### ISSUE THREAD

**Issue by jvoisin** [daanx/mimalloc-bench#103]
[rocksdb]( https://en.wikipedia.org/wiki/RocksDB) has a [neat benchmarking tool]( https://github.com/facebook/rocksdb/wiki/Benchmarking-tools ), and it written with hardware-efficiency in mind, so it should highlight some allocators shortcoming.

Moreover, it's buildable with a makefile, so integrating it shouldn't be hard.

**Comment by tvaleev** [comment]
The main question what tests are needed to add and run from rocksdb benchmarking tool?
Currently I added:
`db_bench --benchmarks=fillrandom -- write N values in random key order in async mode`

**Comment by jvoisin** [comment]
Looks good to me :)
