### ISSUE TITLE
Add the new TCMalloc

### ISSUE THREAD

**Issue by RedBeard0531** [daanx/mimalloc-bench#108]
Unfortunately, there are two allocators both called tcmalloc. You are using the one from the gperftools repo, but a newer fork from upstream which uses restartable sequences is available at https://github.com/google/tcmalloc. It would be nice to be able to see results for both of them along with mimalloc.

**Comment by jvoisin** [comment]
Google is maintaining two versions of tcmalloc?

**Comment by RedBeard0531** [comment]
I can't speak for what Google is maintaining. However, that repo is under the Google org on github, while gperftools has its own org. Also, the first lines of the gperftools readme say 

```
gperftools
----------
(originally Google Performance Tools)
```

https://github.com/gperftools/gperftools/blob/e80652b6279a22bd4a4264e4403cd1981293e82f/README#L1-L3

**Comment by alphanso** [comment]
https://github.com/google/tcmalloc/issues/2

Above issue discuss the difference between the two tcmalloc

**Comment by jvoisin** [comment]
I managed to build a `.so`, I'll try to clean my scripts up, and send a pull-request ~tomorrow (famous last words).

For the record, the patch looks like this:

```diff
diff --git a/tcmalloc/BUILD b/tcmalloc/BUILD
index 2114359..1fe14d2 100644
--- a/tcmalloc/BUILD
+++ b/tcmalloc/BUILD
@@ -83,7 +83,7 @@ tcmalloc_deps = [
 ]
 
 # This library provides tcmalloc always
-cc_library(
+cc_binary(
     name = "tcmalloc",
     srcs = [
         "libc_override.h",
@@ -94,12 +94,11 @@ cc_library(
         "tcmalloc.h",
     ],
     copts = TCMALLOC_DEFAULT_COPTS,
-    linkstatic = 1,
     visibility = ["//visibility:public"],
     deps = tcmalloc_deps + [
         ":common",
     ],
-    alwayslink = 1,
+    linkshared = True,
 )
```
