### ISSUE TITLE
new[] and delete in Larson.cpp

### ISSUE THREAD

**Issue by mjp41** [daanx/mimalloc-bench#13]
@daanx the Larson benchmarking does not correctly match `new[]` to `delete[]` calls.  It allocates as an array, but deletes as an object: For instance allocation here

https://github.com/daanx/mimalloc-bench/blob/bcddf9f54d3a1e4271da1cf1ad7966514ed860c9/bench/larson/larson.cpp#L379

and deallocation here

https://github.com/daanx/mimalloc-bench/blob/bcddf9f54d3a1e4271da1cf1ad7966514ed860c9/bench/larson/larson.cpp#L391

This means that it is supplying size parameters to `delete` assuming it is deallocating a `char` rather than a `char` array.  For `snmalloc` this was causing a lot of memory wastage as it was assuming the `size` was correct.

I am happy to PR a fix, but wanted to check if you would take it.

**Comment by daanx** [comment]
Thanks Matthew, hope everything is well with you :-)
Ah awesome for finding this -- yes please send a PR (I am currently working on other things) and of course I will take it in.

**Comment by mjp41** [comment]
Most allocators probably ignore the size parameter, but it could be a problem for mimalloc, if it changes mode between the array size and the element size.

I've submitted a PR #14.

**Comment by daanx** [comment]
Thanks for the PR!
