### ISSUE TITLE
lean-mathlib not correctly set up

### ISSUE THREAD

**Issue by derSteFfi** [daanx/mimalloc-bench#195]
after running `./build-bench-env.sh lean`, the benchmarking script complains about `$leandir/../mathlib` being missing. After creating it manually, `leanpkg.toml` is not found. I manually copied the file from `$leandir/leanpkg/` into `mathlib` which resulted in a running benchmark. Not sure if that's the intended way though. However, `build-bench-ev.sh` should take care of that.

**Comment by jvoisin** [comment]
Care to send a pull-request to fix this?
