### ISSUE TITLE
Please consider adding scudo

### ISSUE THREAD

**Issue by joshtriplett** [daanx/mimalloc-bench#21]
Please consider adding the scudo allocator. It's available in the `compiler-rt/lib/scudo/standalone` directory of https://github.com/llvm/llvm-project/ , and from that directory, you can build a shared library using `clang++ -flto -fuse-ld=lld -fPIC -std=c++14 -fno-exceptions -fno-rtti -fvisibility=internal -msse4.2 -O3 -I include -shared -o libscudo.so *.cpp -pthread`

**Comment by daanx** [comment]
Thanks for the suggestion @joshtriplett -- and apologies for the late reply (replies!); I was accidently not "watching" this repo but will try to catch up :-)  If I get to it I will include it as well!

**Comment by AndroidInternal** [comment]
scudo is now the default allocator on Android and Fuchsia.

According to this [article](http://expertmiami.blogspot.com/2019/05/what-is-scudo-hardened-allocator_10.html)，scudo's performance is pretty good.

Please consider adding the scudo allocator.

**Comment by jvoisin** [comment]
Sparse checkouts to the rescue:

```
git init llvm-project
cd llvm-project
git remote add -f origin https://github.com/llvm/llvm-project
git config core.sparseCheckout true
echo "main/compiler-rt/lib/scudo/standalone" >> .git/info/sparse-checkout
```

I might™ do this at some point, but feel free to proceed without me.
