### ISSUE TITLE
need new allocators

### ISSUE THREAD

**Issue by osevan** [daanx/mimalloc-bench#24]
Update allocator list with

https://www.qt.io/blog/a-fast-and-thread-safe-pool-allocator-for-qt-part-1

According of coder fastest allocator. 

And tcmalloc latest available from github source 

And if scalloc fails with GCc 10.2 install automaticaly GCC 8 and  build specific with gcc-8 g++-8 with CC=GCC-8 CXX=g++-8

It.should.build

**Comment by daanx** [comment]
tcmalloc is updated; if you like to add other allocators please send a PR.
