### ISSUE TITLE
http://www.microquill.com seems not accessible

### ISSUE THREAD

**Issue by devnexen** [daanx/mimalloc-bench#26]
is there any known alternative URL eventually ?

**Comment by daanx** [comment]
ah, that is a shame; I do not know of an alternative URL -- it probably does not exist as the header says explicitly:
```
* This source code, or source code derived from it, may not be redistributed 
* without express written permission of the copyright owner.
```
fingers crossed that it comes back up as these are interesting benchmarks.

**Comment by daanx** [comment]
I just tried today and it seems to work again so I am going to close this for now
