### ISSUE TITLE
Add glibc's malloc tests

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [daanx/mimalloc-bench#27]
Please add both of glibc's malloc tests for all of the allocators:

1. glibc/benchtests/bench-malloc-simple.c
2. glibc/benchtests/bench-malloc-thread.c

Get them here: https://www.gnu.org/software/libc/sources.html:
```
git clone https://sourceware.org/git/glibc.git
cd glibc
git checkout master
```
Mirror: https://github.com/bminor/glibc/tree/master/benchtests

See also: 
1. https://kazoo.ga/a-simple-tool-to-test-malloc-performance/
2. https://github.com/f18m/malloc-benchmarks/tree/master/benchmark-src

**Comment by daanx** [comment]
Added them -- thanks for bringing it to my attention
