### ISSUE TITLE
Hardcoded path for LD_PRELOAD 

### ISSUE THREAD

**Issue by jserv** [daanx/mimalloc-bench#4]
I can build part of `mimalloc-bench` on Linux/Aarch64 target. However, I found hardcoded path for `LD_PRELOAD`:
```
out/bench$ ../../bench.sh rp cfrac
...
---- cfrac

run cfrac rp: LD_PRELOAD=/tmp/mimalloc-bench/extern/rpmalloc/bin/linux/release/x86-64/librpmalloc.so ./cfrac 175451865205073170563711388363274837927895
ERROR: ld.so: object '/tmp/mimalloc-bench/extern/rpmalloc/bin/linux/release/x86-64/librpmalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
````

It should not be `x86-64` since I am testing `aarch64`.

**Comment by daanx** [comment]
Ah., I'll try fix that, it should refer directy to the rpmalloc in `"$localdevdir/rpmalloc/build/..."`, and also, it should use the `librpmallocwrap.so` to properly override!

**Comment by daanx** [comment]
If you can fix it locally, please create a pull request as I currently cannot build rpmalloc with clang 3.8.0 which somehow fails on rpmalloc with:
```
error: support for type '__float128' is not yet implemented
  abs(__float128 __x)
```

**Comment by daanx** [comment]
Should be fixed by now (using the `find` command)
