### ISSUE TITLE
Use full names for allocators

### ISSUE THREAD

**Issue by jvoisin** [daanx/mimalloc-bench#58]
Currently, it's a bit confusing what the two-letter codes are referring to: what are the differences between `mi`, `xdmi`, `xmi`, `dmi`, `smi`, `xsmi`, … also, what is `sc` compared to `scudo`? What is `tlsf` ? And so on.

I would have been happy to do it myself, but for some allocators, I actually have no clue what they're referring to :D

**Comment by daanx** [comment]
Ah, I like the short names especially when looking at benchmark results or specifying them on the command line. How about I add a little mapping for short + long names so both can be used on the command line.

Btw: `smi` is for mimalloc in secure mode, `dmi` in debug mode where I use the benchmarks as a test-suite for mimalloc. the `xmi` is for being able to run mimalloc in development so it can be directly compared against a stable version. `sc` is the `scalloc` allocator btw

**Comment by jvoisin** [comment]
Oh, I have no issue with small command line parameters, since they're documented in the `--help`. My grief comes from the benchmark results (from #57 )

![xxx](https://user-images.githubusercontent.com/325724/142771584-8ee89189-9f49-4783-89d0-2baf1d5c280e.png)

where it's non-trivial for the casual reader to understand what `sm`, `sn`, … are referring to.
