### ISSUE TITLE
Mention which allocators need system-wide install

### ISSUE THREAD

**Issue by mratsim** [daanx/mimalloc-bench#9]
For those not on Debian/Ubuntu it would be very helpful to know which allocators need to be installed system-wide and which are fetched by the build script.

Even better would be to split that script into a local build script that work on any Linux and isolate the parts that assumes Debian/Ubuntu. It would be easier for others to then add the scripts for Arch, Fedora, Gentoo, ...

**Comment by daanx** [comment]
I see! Sorry for the late reply -- it seemed I wasn't getting notifications on this repo :-(
Anyway, I am not a unix expert and it is hard to fix this for me but any PR's are welcome -- thanks @bpowers for making a patch for Fedora!
